### ISSUE TITLE
Crashing when loading skinned player head tile entities

### ISSUE THREAD

**Issue by asier-ochoa** [edoren/SkinChanger#9]
The game crashes whenever a structure mod generates a player head with a skin. When Dungeons Arise's structures do this to decorate the structures.

Here is my crash report:
```---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 5/5/21 1:14 PM
Description: Rendering Block Entity

java.lang.NullPointerException: Rendering Block Entity
	at me.edoren.skin_changer.common.models.PlayerModel.hashCode(PlayerModel.java:31) ~[skin_changer:0.2.0] {re:classloading}
	at java.util.HashMap.hash(Unknown Source) ~[?:1.8.0_291] {}
	at java.util.HashMap.get(Unknown Source) ~[?:1.8.0_291] {}
	at me.edoren.skin_changer.client.api.SkinLoaderService.getSkin(SkinLoaderService.java:99) ~[skin_changer:0.2.0] {re:classloading}
	at me.edoren.skin_changer.client.ClientController.getLocationSkin(ClientController.java:45) ~[skin_changer:0.2.0] {re:classloading}
	at me.edoren.skin_changer.client.ClientASMHooks.getRenderTypeSkull(ClientASMHooks.java:29) ~[skin_changer:0.2.0] {re:classloading}
	at net.minecraft.client.renderer.tileentity.SkullTileEntityRenderer.func_228878_a_(SourceFile:103) ~[?:?] {re:classloading,xf:fml:skin_changer:Transformer002}
	at net.minecraft.client.renderer.tileentity.SkullTileEntityRenderer.func_228879_a_(SourceFile:86) ~[?:?] {re:classloading,xf:fml:skin_changer:Transformer002}
	at net.minecraft.client.renderer.tileentity.SkullTileEntityRenderer.func_225616_a_(SourceFile:65) ~[?:?] {re:classloading,xf:fml:skin_changer:Transformer002}
	at net.minecraft.client.renderer.tileentity.SkullTileEntityRenderer.func_225616_a_(SourceFile:29) ~[?:?] {re:classloading,xf:fml:skin_changer:Transformer002}
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_228855_a_(TileEntityRendererDispatcher.java:126) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.lambda$renderTileEntity$0(TileEntityRendererDispatcher.java:101) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_228853_a_(TileEntityRendererDispatcher.java:185) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_228850_a_(TileEntityRendererDispatcher.java:99) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.renderer.WorldRenderer.func_228426_a_(WorldRenderer.java:1814) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:A}
	at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:1022) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,xf:fml:xaerominimap:xaero_gamerenderer_resetprojectionmatrix,xf:fml:xaerominimap:xaero_gamerenderer_renderworld,pl:mixin:APP:totaldarkness.mixins.json:MixinGameRenderer,pl:mixin:APP:create.mixins.json:StoreProjectionMatrixMixin,pl:mixin:A}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:693) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,xf:fml:xaerominimap:xaero_gamerenderer_resetprojectionmatrix,xf:fml:xaerominimap:xaero_gamerenderer_renderworld,pl:mixin:APP:totaldarkness.mixins.json:MixinGameRenderer,pl:mixin:APP:create.mixins.json:StoreProjectionMatrixMixin,pl:mixin:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:976) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[minecraft-1.16.5-client.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_291] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_291] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_291] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_291] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.5-36.1.0-launcher.jar:36.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:50) [ForgeWrapper-1.4.2.jar:?] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_291] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_291] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_291] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_291] {}
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?] {}
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?] {}
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?] {}
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at me.edoren.skin_changer.common.models.PlayerModel.hashCode(PlayerModel.java:31) ~[skin_changer:0.2.0] {re:classloading}
	at java.util.HashMap.hash(Unknown Source) ~[?:1.8.0_291] {}
	at java.util.HashMap.get(Unknown Source) ~[?:1.8.0_291] {}
	at me.edoren.skin_changer.client.api.SkinLoaderService.getSkin(SkinLoaderService.java:99) ~[skin_changer:0.2.0] {re:classloading}
	at me.edoren.skin_changer.client.ClientController.getLocationSkin(ClientController.java:45) ~[skin_changer:0.2.0] {re:classloading}
	at me.edoren.skin_changer.client.ClientASMHooks.getRenderTypeSkull(ClientASMHooks.java:29) ~[skin_changer:0.2.0] {re:classloading}
	at net.minecraft.client.renderer.tileentity.SkullTileEntityRenderer.func_228878_a_(SourceFile:103) ~[?:?] {re:classloading,xf:fml:skin_changer:Transformer002}
	at net.minecraft.client.renderer.tileentity.SkullTileEntityRenderer.func_228879_a_(SourceFile:86) ~[?:?] {re:classloading,xf:fml:skin_changer:Transformer002}
	at net.minecraft.client.renderer.tileentity.SkullTileEntityRenderer.func_225616_a_(SourceFile:65) ~[?:?] {re:classloading,xf:fml:skin_changer:Transformer002}
	at net.minecraft.client.renderer.tileentity.SkullTileEntityRenderer.func_225616_a_(SourceFile:29) ~[?:?] {re:classloading,xf:fml:skin_changer:Transformer002}
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_228855_a_(TileEntityRendererDispatcher.java:126) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.lambda$renderTileEntity$0(TileEntityRendererDispatcher.java:101) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
-- Block Entity Details --
Details:
	Name: minecraft:skull // net.minecraft.tileentity.SkullTileEntity
	Block: Block{minecraft:player_head}[rotation=6]
	Block location: World: (-9,63,-311), Chunk: (at 7,3,9 in -1,-20; contains blocks -16,0,-320 to -1,255,-305), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Block: Block{minecraft:player_head}[rotation=6]
	Block location: World: (-9,63,-311), Chunk: (at 7,3,9 in -1,-20; contains blocks -16,0,-320 to -1,255,-305), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
Stacktrace:
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_228853_a_(TileEntityRendererDispatcher.java:185) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_228850_a_(TileEntityRendererDispatcher.java:99) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.renderer.WorldRenderer.func_228426_a_(WorldRenderer.java:1814) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:A}
	at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:1022) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,xf:fml:xaerominimap:xaero_gamerenderer_resetprojectionmatrix,xf:fml:xaerominimap:xaero_gamerenderer_renderworld,pl:mixin:APP:totaldarkness.mixins.json:MixinGameRenderer,pl:mixin:APP:create.mixins.json:StoreProjectionMatrixMixin,pl:mixin:A}


-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['smug_twingo'/659, l='ClientLevel', x=-59.30, y=62.75, z=-274.70]]
	Chunk stats: Client Chunk Cache: 729, 462
	Level dimension: minecraft:overworld
	Level spawn location: World: (-64,66,-256), Chunk: (at 0,4,0 in -4,-16; contains blocks -64,0,-256 to -49,255,-241), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 8933 game time, 8933 day time
	Server brand: forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:617) ~[?:?] {re:mixin,re:classloading,xf:OptiFine:default,xf:fml:xaeroworldmap:xaero_wm_clientworldclass,xf:fml:xaerominimap:xaero_clientworldclass,pl:mixin:APP:abnormals_core.mixins.json:client.ClientWorldMixin,pl:mixin:APP:enhancedcelestials.mixins.json:client.MixinClientWorld,pl:mixin:A}
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2029) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:623) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[minecraft-1.16.5-client.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_291] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_291] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_291] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_291] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.5-36.1.0-launcher.jar:36.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:50) [ForgeWrapper-1.4.2.jar:?] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_291] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_291] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_291] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_291] {}
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?] {}
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?] {}
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?] {}
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?] {}


-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_291, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 8514411160 bytes (8119 MB) / 12582912000 bytes (12000 MB) up to 12582912000 bytes (12000 MB)
	CPUs: 12
	JVM Flags: 21 total; -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms12000m -Xmx12000m
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.1.0-launcher.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.1.0-launcher.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.1.0-launcher.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.1.0-launcher.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine_1.16.5_HD_U_G7.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.1.0-launcher.jar fml TRANSFORMATIONSERVICE 
	FML: 36.1
	Forge: net.minecraftforge:36.1.0
	FML Language Providers: 
		javafml@36.1
		minecraft@1
	Mod List: 
		skin_changer-0.2.0.jar                            |Skin Changer                  |skin_changer                  |0.2.0               |DONE      |NOSIGNATURE
		jei-1.16.5-7.6.4.86.jar                           |Just Enough Items             |jei                           |7.6.4.86            |DONE      |NOSIGNATURE
		the-conjurer-1.16.4-1.0.13.jar                    |The Conjurer                  |conjurer_illager              |1.0.13              |DONE      |NOSIGNATURE
		abnormals_core-1.16.5-3.1.1.jar                   |Abnormals Core                |abnormals_core                |3.1.1               |DONE      |NOSIGNATURE
		buzzier_bees-1.16.5-3.0.1.jar                     |Buzzier Bees                  |buzzier_bees                  |3.0.1               |DONE      |NOSIGNATURE
		Bayou-Blues-1.16.5-1.0.4.jar                      |Bayou Blues                   |bayou_blues                   |1.16.5-1.0.4        |DONE      |NOSIGNATURE
		findme-1.16.3-2.2.0.0.jar                         |Find Me                       |findme                        |2.2.0               |DONE      |NOSIGNATURE
		create-mc1.16.5_v0.3.1b.jar                       |Create                        |create                        |mc1.16.5_v0.3.1b+143|DONE      |NOSIGNATURE
		BetterCaves-Forge-1.16.4-1.1.1.jar                |YUNG's Better Caves           |bettercaves                   |1.16.4-1.1.1        |DONE      |NOSIGNATURE
		totaldarkness-1.3-1.16.5.jar                      |Total Darkness                |totaldarkness                 |1.3-1.16.5          |DONE      |NOSIGNATURE
		XaerosWorldMap_1.13.2_Forge_1.16.5.jar            |Xaero's World Map             |xaeroworldmap                 |1.13.2              |DONE      |NOSIGNATURE
		Placebo-1.16.4-4.4.2.jar                          |Placebo                       |placebo                       |4.4.2               |DONE      |NOSIGNATURE
		citadel-1.6.2.jar                                 |Citadel                       |citadel                       |1.6.2               |DONE      |NOSIGNATURE
		alexsmobs-1.10.0.jar                              |Alex's Mobs                   |alexsmobs                     |1.10.0              |DONE      |NOSIGNATURE
		NaturesCompass-1.16.5-1.8.6.jar                   |Nature's Compass              |naturescompass                |1.16.5-1.8.6        |DONE      |NOSIGNATURE
		YungsApi-1.16.4-Forge-6.jar                       |YUNG's API                    |yungsapi                      |1.16.4-Forge-6      |DONE      |NOSIGNATURE
		Wither-Skeleton-Tweaks-1.16.4-5.3.0.jar           |Wither Skeleton Tweaks        |wstweaks                      |5.3.0               |DONE      |NOSIGNATURE
		u_team_core-1.16.4-3.1.17.192.jar                 |U Team Core                   |uteamcore                     |3.1.17.192          |DONE      |f4:a6:0b:ee:cb:8a:1a:ea:9f:9d:45:91:8f:8b:b3:ae:26:f3:bf:05:86:1d:90:9e:f6:32:2a:1a:ed:1d:ce:b0
		Apotheosis-1.16.4-4.5.2.jar                       |Apotheosis                    |apotheosis                    |4.5.2               |DONE      |NOSIGNATURE
		allurement-1.16.5-1.1.1.jar                       |Allurement                    |allurement                    |1.1.1               |DONE      |NOSIGNATURE
		JustEnoughResources-1.16.4-0.12.0.109.jar         |Just Enough Resources         |jeresources                   |0.12.0.109          |DONE      |NOSIGNATURE
		BetterThanMending-1.6.0.jar                       |BetterThanMending             |betterthanmending             |1.6.0               |DONE      |NOSIGNATURE
		forge-1.16.5-36.1.0-universal.jar                 |Forge                         |forge                         |36.1.0              |DONE      |22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		netherite-plus-mod-1.4.3-1.16.5-forge.jar         |Netherite Plus                |netherite_plus                |1.4.3-1.16.5        |DONE      |NOSIGNATURE
		betterendforge-1.16.4-1.5.1.jar                   |BetterEnd Forge               |betterendforge                |1.16.4-1.5.1        |DONE      |NOSIGNATURE
		tellme-forge-1.16.4-0.9.1.jar                     |TellMe                        |tellme                        |0.9.1               |DONE      |NOSIGNATURE
		structure_gel-1.16.5-1.7.7.jar                    |Structure Gel API             |structure_gel                 |1.7.7               |DONE      |NOSIGNATURE
		dungeonsarise1.16.5-1.2.68a-HF.jar                |Dungeons Arise                |dungeons_arise                |1.2.68a             |DONE      |NOSIGNATURE
		BetterPingDisplay-1.16.4-1.0.jar                  |Better Ping Display           |betterpingdisplay             |1.0                 |DONE      |NOSIGNATURE
		forge-1.16.5-36.1.0-client.jar                    |Minecraft                     |minecraft                     |1.16.5              |DONE      |NOSIGNATURE
		cofh_core-1.16.4-1.2.1.jar                        |CoFH Core                     |cofh_core                     |1.2.1               |DONE      |NOSIGNATURE
		customizableelytra-1.16.4-1.4.3.jar               |Customizable Elytra           |customizableelytra            |1.16.4-1.4.3        |DONE      |NOSIGNATURE
		useful_backpacks-1.16.4-1.11.6.86.jar             |Useful Backpacks              |usefulbackpacks               |1.11.6.86           |DONE      |f4:a6:0b:ee:cb:8a:1a:ea:9f:9d:45:91:8f:8b:b3:ae:26:f3:bf:05:86:1d:90:9e:f6:32:2a:1a:ed:1d:ce:b0
		voicechat-1.16.5-1.1.5.jar                        |Simple Voice Chat             |voicechat                     |1.16.5-1.1.5        |DONE      |NOSIGNATURE
		Abundance-1.16.5-1.0.5.jar                        |Abundance                     |abundance                     |1.16.5-1.0.5        |DONE      |NOSIGNATURE
		useful_railroads-1.16.4-1.4.6.35.jar              |Useful Railroads              |usefulrailroads               |1.4.6.35            |DONE      |f4:a6:0b:ee:cb:8a:1a:ea:9f:9d:45:91:8f:8b:b3:ae:26:f3:bf:05:86:1d:90:9e:f6:32:2a:1a:ed:1d:ce:b0
		BiomesOPlenty-1.16.5-13.1.0.459-universal.jar     |Biomes O' Plenty              |biomesoplenty                 |1.16.4-13.0.0.439   |DONE      |NOSIGNATURE
		valhelsia_structures-16.0.5.jar                   |Valhelsia Structures          |valhelsia_structures          |16.0.5              |DONE      |NOSIGNATURE
		dungeons_plus-1.16.5-1.1.4.jar                    |Dungeons Plus                 |dungeons_plus                 |1.1.4               |DONE      |NOSIGNATURE
		archers_paradox-1.16.4-1.2.0.jar                  |Archer's Paradox              |archers_paradox               |1.2.0               |DONE      |NOSIGNATURE
		SimpleLogin-1.16-0.0.0.jar                        |Simple Login                  |simplelogin                   |0.0.0               |DONE      |NOSIGNATURE
		savageandravage-1.16.5-3.1.0.jar                  |Savage & Ravage               |savageandravage               |3.1.0               |DONE      |NOSIGNATURE
		Patchouli-1.16.4-50 (1).jar                       |Patchouli                     |patchouli                     |1.16.4-50           |DONE      |NOSIGNATURE
		Xaeros_Minimap_21.6.0_Forge_1.16.5.jar            |Xaero's Minimap               |xaerominimap                  |21.6.0              |DONE      |NOSIGNATURE
		leap-1.16.4-1.1.1.jar                             |Leap                          |leap                          |1.1.1               |DONE      |NOSIGNATURE
		autumnity-1.16.5-2.1.1.jar                        |Autumnity                     |autumnity                     |2.1.1               |DONE      |NOSIGNATURE
		AutoRegLib-1.6-47.jar                             |AutoRegLib                    |autoreglib                    |1.6-47              |DONE      |NOSIGNATURE
		Quark-r2.4-310.jar                                |Quark                         |quark                         |r2.4-310            |DONE      |NOSIGNATURE
		Chunk+Pregenerator-V1.16-3.0.5.jar                |Chunk Pregenerator            |chunkpregen                   |V1.16-3.0.5         |DONE      |NOSIGNATURE
		BetterStrongholds-1.16.4-1.0.1.jar                |YUNG's Better Strongholds     |betterstrongholds             |1.16.4-1.0.1        |DONE      |NOSIGNATURE
		TheAbyss2+1.9.7+1.16.5.jar                        |TheAbyss                      |theabyss                      |1.9.7               |DONE      |NOSIGNATURE
		architectury-1.12.145-forge.jar                   |Architectury                  |architectury                  |1.12.145            |DONE      |NOSIGNATURE
		ftb-gui-library-1605.2.1.41-forge.jar             |FTB GUI Library               |ftbguilibrary                 |1605.2.1.41         |DONE      |NOSIGNATURE
		AppleSkin-mc1.16.2-forge-1.0.14.jar               |AppleSkin                     |appleskin                     |1.0.14              |DONE      |NOSIGNATURE
		AI-Improvements-1.16.2-0.3.0.jar                  |AI-Improvements               |aiimprovements                |0.3.0               |DONE      |NOSIGNATURE
		DamageTilt-1.16-forge-0.1.1.jar                   |DamageTilt                    |damagetilt                    |0.1.1               |DONE      |NOSIGNATURE
		enhancedcelestials-1.0.4-1.16.4.jar               |Enhanced Celestials           |enhancedcelestials            |1.0.4-1.16.4        |DONE      |NOSIGNATURE
		SoundFilters-0.14_for_1.16.2.jar                  |Sound Filters                 |soundfilters                  |0.14_for_1.16.2     |DONE      |NOSIGNATURE
		ServerTabInfo-1.16.4-1.3.3.jar                    |Server Tab Info               |servertabinfo                 |1.3.3               |DONE      |NOSIGNATURE
		GameMenuModOption-1.16.4-1.8.jar                  |Game Menu Mod Option          |gamemenumodoption             |1.8                 |DONE      |NOSIGNATURE
		BetterMineshafts-Forge-1.16.4-2.0.3.jar           |YUNG's Better Mineshafts      |bettermineshafts              |1.16.4-2.0.3        |DONE      |NOSIGNATURE
		balancedenchanting-1.0.jar                        |Balanced Enchanting           |balancedenchanting            |1.0                 |DONE      |NOSIGNATURE
	Crash Report UUID: 8b00649e-405e-490c-9e95-3b23d0063ee1
	Patchouli open book context: n/a
	Launched Version: MultiMC5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce RTX 2070 with Max-Q Design/PCIe/SSE2 GL version 4.6.0 NVIDIA 460.89, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, mod_resources, quark:emote_resources (incompatible), file/ComplementaryResources 3.13
	Current Language: English (US)
	CPU: 12x Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
	OptiFine Version: OptiFine_1.16.5_HD_U_G7
	OptiFine Build: 20210305-003221
	Render Distance Chunks: 32
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 460.89
	OpenGlRenderer: GeForce RTX 2070 with Max-Q Design/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 12```

**Comment by 1101331** [comment]
Actually im not sure if the structure comes from valhelsia, might be dungeons plus

**Comment by edoren** [comment]
I need to research further into this, can you provide me steps on how to reproduce it?

**Comment by edoren** [comment]
Might be related to https://github.com/edoren/SkinChanger/issues/5

**Comment by edoren** [comment]
Just release a new version v0.2.2, please try using it.

**Comment by MatsuoYutani** [comment]
Hello! I'm using v0.2.2 and just had a similar crash, not sure if I should open another issue.

Instead of getting a 'java.lang.NullPointerException: Rendering Block Entity', i've got a 'java.lang.NullPointerException: Rendering item'.

I crash everytime I press 'U' on any head to see recipes on JEI.

[crash-2021-09-19_11.49.45-client.txt](https://github.com/edoren/SkinChanger/files/7192317/crash-2021-09-19_11.49.45-client.txt)

**Comment by edoren** [comment]
This should be fixed on latest versions.
